# Generated by Django 3.1 on 2020-10-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201018_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
